package internal

import (
	"crypto/rand"
	"encoding/binary"
	"fmt"
)

// Server-generated slug wordlist. 1000 adjectives × 1000 nouns = 1,000,000
// combinations. Per SPEC §POST /api/compose, the collision retry budget
// is 5 attempts; at 1M combinations the collision probability stays
// negligible even under heavy load.
//
// Words are plain ASCII, short, memorable, napkin-writable. No hyphens
// inside individual words; the join character is the only hyphen in
// the final slug.

var slugAdjectives = []string{
	"amber", "ancient", "quiet", "bright", "calm", "clear", "cold", "crisp",
	"dark", "deep", "distant", "dusty", "early", "empty", "faint", "fair",
	"fallen", "far", "fine", "fresh", "gentle", "golden", "grand", "grave",
	"green", "grey", "happy", "hidden", "high", "hollow", "honest", "humble",
	"icy", "idle", "inner", "jagged", "kind", "late", "light", "little",
	"lonely", "long", "loose", "loud", "low", "lucid", "lucky", "lush",
	"main", "mellow", "mild", "misty", "moonlit", "muted", "narrow", "near",
	"new", "old", "open", "pale", "patient", "plain", "plum", "polar",
	"pretty", "prime", "proud", "pure", "quaint", "quick", "quirky", "raw",
	"red", "rich", "rosy", "rough", "royal", "rustic", "sable", "safe",
	"secret", "sharp", "shy", "silent", "silver", "simple", "slow", "small",
	"smooth", "snowy", "soft", "solid", "spare", "still", "stout", "sunny",
	"sweet", "tender", "thin", "tidy", "able", "actual", "agile", "airy",
	"alert", "alive", "apt", "ardent", "arid", "assured", "avid", "awake",
	"aware", "banded", "bare", "basic", "bold", "breezy", "brisk", "broad",
	"bronze", "brown", "buoyant", "candid", "central", "chosen", "clean", "clever",
	"close", "coastal", "common", "cool", "coral", "cosmic", "cozy", "cubic",
	"curvy", "dainty", "dapper", "dear", "decent", "devoted", "direct", "divine",
	"docile", "domestic", "dotted", "durable", "eager", "earnest", "easy", "elastic",
	"elegant", "ample", "even", "exact", "expert", "extra", "famous", "fancy",
	"fast", "fiery", "fixed", "flat", "fleet", "floral", "fluid", "fond",
	"formal", "forward", "free", "frosted", "full", "giving", "glad", "glassy",
	"gleaming", "global", "glossy", "good", "graceful", "gracious", "great", "genuine",
	"gritty", "hardy", "hasty", "hearty", "heavy", "helpful", "hopeful", "ideal",
	"infant", "intact", "jovial", "just", "keen", "known", "large", "lasting",
	"lavish", "lean", "level", "linear", "lively", "lunar", "lyric", "magic",
	"major", "marble", "marked", "massive", "mature", "mindful", "minimal", "mobile",
	"modest", "mossy", "motley", "moving", "natural", "noble", "nordic", "noted",
	"novel", "now", "obvious", "ornate", "outdoor", "oval", "outer", "pacific",
	"passive", "pastoral", "peaceful", "pebbled", "perfect", "perky", "pleasant", "polished",
	"positive", "potent", "precise", "primal", "placid", "prompt", "proper", "proven",
	"radiant", "rapid", "rare", "ready", "real", "regal", "remote", "resilient",
	"restful", "ripe", "robust", "round", "rugged", "rural", "scenic", "serene",
	"settled", "shady", "shining", "sleek", "slender", "slim", "smart", "soaring",
	"solemn", "soothing", "sparse", "steady", "stoic", "strong", "subtle", "supple",
	"swift", "tactful", "tall", "tame", "tan", "thorough", "timely", "tranquil",
	"trim", "true", "trusted", "unique", "united", "upbeat", "upright", "urban",
	"useful", "vast", "verdant", "vibrant", "vital", "vivid", "warm", "welcome",
	"whole", "wide", "wild", "willing", "wise", "wonderful", "wooden", "worldly",
	"worthy", "youthful", "zesty", "zero", "zonal", "zippy", "blithe", "bonny",
	"bouncy", "bountiful", "bracing", "brazen", "burnished", "carefree", "careful", "casual",
	"centered", "certain", "charmed", "cheerful", "civic", "classic", "collected", "compact",
	"composed", "concise", "confident", "content", "cordial", "creative", "cultured", "curious",
	"cutting", "deft", "dew", "diligent", "distinct", "dreamy", "driven", "enduring",
	"energetic", "engaging", "etched", "eternal", "faithful", "familiar", "farther", "festive",
	"fleeting", "flexible", "flourishing", "flowing", "focused", "forested", "forthright", "friendly",
	"frugal", "fulfilled", "fundamental", "gifted", "gleeful", "glowing", "grounded", "growing",
	"guided", "hallowed", "handy", "harmless", "healing", "healthy", "hushed", "illustrious",
	"immense", "infinite", "ingenious", "inspired", "inventive", "inviting", "irenic", "jubilant",
	"knightly", "knowing", "lauded", "layered", "leafy", "learned", "leisurely", "limber",
	"linked", "lofty", "logical", "loyal", "luminous", "magnetic", "majestic", "moderate",
	"moist", "moral", "motivated", "nascent", "neat", "needed", "nimble", "nominal",
	"nourished", "nurturing", "objective", "observant", "optimal", "orderly", "organized", "original",
	"outstretched", "overall", "perennial", "pivotal", "playful", "poised", "popular", "pragmatic",
	"present", "prized", "productive", "prudent", "refined", "relaxed", "reliable", "reserved",
	"resonant", "responsive", "rightful", "rising", "rooted", "rounded", "sacred", "sage",
	"seasonal", "selective", "sensible", "shared", "sincere", "skilled", "sociable", "solar",
	"sound", "stable", "stellar", "structured", "subdued", "supportive", "sustainable", "thoughtful",
	"timeless", "tolerant", "touched", "trademark", "trained", "tuneful", "typical", "ultimate",
	"unbroken", "unified", "uplifting", "utmost", "valid", "valued", "venerable", "versatile",
	"vigorous", "visible", "vocal", "welcoming", "winding", "wistful", "witty", "wonder",
	"yonder", "yielding", "zeal", "zenith", "abiding", "above", "absorbing", "abundant",
	"accented", "acclaimed", "achievable", "active", "admired", "adorned", "advanced", "affecting",
	"affable", "affirmed", "ageless", "airborne", "aloft", "amble", "amiable", "analogue",
	"anchored", "angelic", "animated", "annual", "aplenty", "apparent", "applied", "approachable",
	"arcane", "arboreal", "archaic", "ardor", "artful", "artisan", "ascendant", "attentive",
	"attuned", "audible", "authentic", "azure", "balmy", "becalmed", "becoming", "bedrock",
	"beloved", "benign", "benevolent", "bespoke", "blissful", "blooming", "bounteous", "brave",
	"brief", "caring", "celebrated", "celestial", "charitable", "charming", "cherished", "civil",
	"clarion", "clement", "cohesive", "colorful", "comforting", "commended", "communal", "consistent",
	"constant", "contemplative", "crafted", "current", "decisive", "dedicated", "dewy", "edifying",
	"effortless", "effulgent", "elevated", "eminent", "empathic", "enabled", "enchanting", "enjoyable",
	"enlightened", "enriched", "equable", "esteemed", "eventful", "everlasting", "excellent", "exemplary",
	"exquisite", "faraway", "fearless", "fertile", "fortunate", "fragrant", "fruitful", "gilded",
	"girlish", "gloried", "grateful", "guileless", "halcyon", "harmonious", "heartfelt", "highland",
	"hospitable", "immaculate", "imperial", "important", "impressible", "improved", "inclusive", "integral",
	"intentional", "laudable", "leading", "legendary", "lenient", "meaningful", "melodic", "merciful",
	"meticulous", "mid", "optimistic", "parental", "peaceable", "persistent", "pinnacle", "pioneering",
	"polite", "powerful", "precious", "progressive", "prolific", "promising", "prosperous", "reassuring",
	"refreshing", "renowned", "respectful", "rewarding", "righteous", "spacious", "spirited", "splendid",
	"spontaneous", "steadfast", "sterling", "storied", "striding", "sturdy", "sublime", "sufficient",
	"superb", "sustaining", "thankful", "thriving", "truthful", "unassuming", "unfolding", "visionary",
	"wholesome", "aerial", "aglow", "alight", "alpine", "angled", "antique", "arched",
	"argent", "aromatic", "ashen", "astute", "august", "auroral", "balanced", "beaming",
	"beige", "birch", "blessed", "boreal", "braided", "chiseled", "chilled", "choral",
	"chunky", "cobalt", "columned", "coppery", "courtly", "crested", "crispy", "cropped",
	"crowned", "cupped", "curved", "cyclic", "dappled", "defined", "dense", "dewed",
	"diaphanous", "dotty", "downy", "draped", "dusky", "earthen", "edged", "elfin",
	"embedded", "emerald", "endowed", "equine", "estival", "expanded", "fabled", "faceted",
	"faded", "feathery", "fervent", "fibrous", "filmy", "flanked", "flecked", "flinty",
	"flooded", "folded", "foreign", "framed", "freckled", "fronded", "frosty", "furled",
	"gauzy", "gemlike", "gnarly", "grained", "granular", "grassy", "gravelly", "grazed",
	"greenlit", "grooved", "hazel", "heathery", "hemmed", "hewn", "hilltop", "hoary",
	"honored", "hovering", "inclined", "inlaid", "inscribed", "insular", "iridescent", "ivory",
	"jointed", "keyed", "knitted", "knotted", "lacquered", "lambent", "latent", "latticed",
	"leafed", "lichened", "lilac", "limned", "loamy", "local", "lonesome", "lowland",
	"maiden", "manifold", "mapped", "marbly", "measured", "meshed", "moored", "morning",
	"mounded", "mulched", "naive", "native", "nearby", "nested", "netted", "nodding",
	"numbered", "oblique", "offbeat", "oldest", "onward", "organic", "palmy", "paneled",
	"papery", "parched", "patchy", "paved", "peaked", "pebbly", "pinned", "pithy",
	"pitted", "plaited", "planked", "pliant", "plumaged", "pointed", "pooled", "porous",
	"saline", "sandy", "sapphire", "satiny", "sculpted", "seeded", "seeping", "shadowed",
	"sheer", "sheeted", "signed", "sinuous", "skirted", "slatted", "sloped", "snug",
	"soaked", "spaced", "spangled", "specked", "spectral", "spiraled", "spired", "spotted",
	"sprung", "squared", "staked", "stamped", "stemmed", "stilled", "stippled", "striated",
	"striped", "summery", "sunlit", "swathed", "swept", "tawny", "terraced", "textured",
	"thatched", "tidal", "tiered", "tinted", "tipped", "topmost", "traced", "tracked",
	"trailing", "tufted", "twined", "twisting", "uncut", "undulant", "unhurried", "unlit",
	"unspoken", "vaulted", "veined", "velvet", "vernal", "virid", "walled", "waxen",
	"wintry", "woven", "wrapped", "yawning", "yielded", "blossomed", "bolted", "canted",
	"carved", "ceiled", "channeled", "chipped", "cladded", "cleared", "clustered", "coated",
	"cobbled", "condensed", "corniced", "coursed", "dashed", "domed", "echoed", "fanned",
	"fenced", "fired", "fitted", "flagged", "furrowed", "gathered", "glazed", "gradual",
	"hued", "inched", "inked", "keeled", "kindled", "lacey", "laureled", "leveled",
	"limbed", "listed", "loaded", "looped", "lowlit", "laced", "marbled", "matted",
	"mirrored", "nodal", "notched", "oaken", "ochre", "opaline", "ovate", "packed",
	"padded", "painted", "penciled", "petaled", "pierced", "piped", "pixeled", "planted",
	"platted", "plated", "plotted", "polled", "pored", "posted", "powered", "primed",
	"printed", "propped", "quarried", "quilted", "raked", "ranked", "reaching", "riveted",
	"roofed", "roped", "rosette", "runged", "salted", "sanded", "scaled", "scattered",
	"scored", "screened", "sealed", "seamed", "shaded", "shallow", "sheaved", "sifted",
	"silted", "sliced", "smoothed", "sorted", "sourced", "spliced", "spread", "stalked",
	"steepled", "stocked", "stoved", "studded", "sunward", "surfaced", "tabled", "tapered",
	"tartan", "threaded", "tiled", "toned", "trellised", "trimmed", "tubular", "tuned",
	"upended", "upswept", "woolly", "winged", "wooded", "yearly", "zoned", "earthy",
}

var slugNouns = []string{
	"anchor", "arbor", "arrow", "autumn", "badge", "basin", "beacon", "beam",
	"bell", "blossom", "bough", "branch", "brook", "canal", "candle", "canyon",
	"cavern", "cedar", "cipher", "clover", "comet", "cove", "creek", "crest",
	"crown", "dawn", "delta", "dune", "dusk", "echo", "ember", "envoy",
	"falcon", "feather", "fen", "fern", "field", "flame", "fog", "forest",
	"fountain", "fox", "garden", "gate", "glade", "glyph", "grove", "harbor",
	"hare", "harp", "hatch", "haven", "hearth", "hedge", "helm", "hollow",
	"horizon", "inlet", "island", "ivy", "lagoon", "lantern", "lark", "ledge",
	"lens", "letter", "light", "lily", "lodge", "loom", "market", "meadow",
	"mesa", "mint", "mirror", "mist", "moon", "moss", "motif", "mountain",
	"nest", "node", "oak", "orbit", "orchard", "otter", "owl", "path",
	"pearl", "petal", "pine", "plaza", "pond", "port", "quarry", "quill",
	"raven", "reed", "ridge", "river", "acorn", "adobe", "agate", "alcove",
	"alder", "almanac", "almond", "altar", "angle", "annex", "anthem", "apex",
	"apiary", "apple", "aqueduct", "arch", "archive", "arena", "ark", "array",
	"ash", "aspen", "atlas", "atoll", "atrium", "avenue", "axle", "balcony",
	"bale", "ballad", "barn", "barrow", "bay", "bayou", "beach", "bead",
	"bearing", "bench", "berry", "bird", "blaze", "bloom", "bluff", "boat",
	"bog", "book", "border", "boulder", "bower", "bridge", "brush", "bud",
	"bulb", "buoy", "cabin", "cairn", "calm", "camp", "cape", "capital",
	"capstone", "card", "cargo", "carpet", "carve", "cascade", "castle", "cave",
	"cell", "chalk", "channel", "chapel", "chart", "chime", "chord", "circle",
	"citrus", "clay", "cliff", "clip", "cloud", "cluster", "cobble", "coin",
	"colony", "column", "commons", "cone", "coral", "cord", "core", "corner",
	"cottage", "course", "court", "crag", "crane", "crater", "crocus", "cross",
	"crystal", "cup", "current", "curve", "cypress", "dell", "den", "depot",
	"dock", "dome", "door", "dove", "draft", "drift", "drum", "earth",
	"eddy", "edge", "elm", "estuary", "expanse", "farm", "ferry", "fiber",
	"fig", "filter", "finch", "fjord", "flag", "flare", "flint", "flora",
	"flute", "foam", "fold", "font", "ford", "forge", "form", "fray",
	"frond", "frost", "fruit", "furrow", "gable", "gap", "gem", "gill",
	"glass", "glow", "gorge", "grain", "granite", "grass", "gravel", "gull",
	"halo", "hamlet", "hand", "heath", "hemp", "herb", "heron", "hill",
	"hive", "hook", "horn", "hull", "hut", "ice", "iris", "iron",
	"jade", "jar", "jasmine", "jetty", "juniper", "keel", "kelp", "kernel",
	"key", "kindle", "knoll", "lace", "lake", "lamp", "land", "lane",
	"larch", "laurel", "lawn", "leaf", "line", "link", "loch", "log",
	"loop", "lotus", "lure", "maple", "margin", "marsh", "mast", "mat",
	"maize", "maze", "mead", "medal", "mill", "moor", "morel", "mortar",
	"mound", "mulch", "nave", "nook", "notch", "oar", "olive", "opal",
	"orchid", "ore", "outpost", "oven", "pace", "paddle", "palm", "panel",
	"peak", "pebble", "perch", "pillar", "pilot", "pit", "plank", "plateau",
	"plinth", "plot", "plume", "point", "pool", "poplar", "porch", "post",
	"pouch", "prairie", "prism", "probe", "prop", "pulse", "pump", "quartz",
	"quarter", "quest", "rail", "range", "rapid", "reach", "reef", "relay",
	"reserve", "ring", "ripple", "road", "rock", "root", "rope", "rose",
	"route", "run", "rush", "rut", "sage", "salt", "sand", "sap",
	"scroll", "seed", "shelf", "shell", "shore", "shrub", "signal", "silt",
	"sketch", "sky", "slate", "slope", "smoke", "snow", "soil", "span",
	"spire", "spoke", "spray", "spring", "spur", "star", "stave", "stem",
	"step", "stone", "strand", "stream", "stump", "summit", "sun", "surface",
	"swamp", "swath", "sweep", "symbol", "table", "tide", "timber", "token",
	"torrent", "tower", "track", "trail", "trawl", "tree", "trellis", "trove",
	"tuft", "twig", "valley", "vault", "veil", "vine", "vista", "warden",
	"wash", "wave", "way", "well", "wheat", "wheel", "willow", "wind",
	"window", "wood", "yarn", "yew", "zone", "abode", "acre", "agar",
	"aim", "air", "aisle", "alley", "alloy", "aloe", "anise", "ant",
	"apse", "aquifer", "arc", "artery", "bat", "bed", "belt", "bend",
	"berth", "board", "bolt", "boom", "booth", "bow", "box", "brine",
	"brow", "bulge", "bulk", "burrow", "bush", "cage", "canopy", "carob",
	"carriage", "cart", "catch", "caulk", "cay", "chair", "charm", "chase",
	"chip", "chill", "clam", "clan", "clasp", "clear", "clearing", "cleft",
	"clew", "climb", "clog", "colt", "comb", "companion", "copy", "couch",
	"courier", "cover", "cowl", "crop", "crook", "cue", "dale", "dam",
	"dash", "datum", "deck", "dew", "dial", "dig", "dike", "dill",
	"dip", "disk", "ditch", "dockyard", "draw", "drill", "drop", "dust",
	"envy", "equinox", "estate", "esteem", "event", "exhibit", "eye", "face",
	"fact", "fair", "fall", "fan", "fare", "fawn", "feat", "fence",
	"ferret", "fetch", "find", "fir", "fish", "fix", "flock", "floor",
	"flow", "flue", "foot", "force", "fork", "frame", "fringe", "front",
	"fund", "garland", "garnet", "gear", "gift", "glean", "glen", "goal",
	"grant", "grift", "grope", "ground", "grout", "guard", "guide", "gulf",
	"gust", "habitat", "haze", "head", "heal", "heap", "height", "hewn",
	"high", "hinge", "hold", "home", "hope", "horde", "hue", "husk",
	"hymn", "ibis", "image", "isle", "islet", "issue", "jaw", "joint",
	"joy", "jungle", "keep", "kindred", "knot", "ladder", "lair", "latch",
	"layer", "legend", "ley", "lift", "limb", "linden", "lint", "list",
	"loft", "lore", "low", "lucent", "luster", "magnet", "manor", "mantle",
	"mark", "meet", "mere", "mesh", "method", "midpoint", "mineral", "moat",
	"mode", "module", "moment", "money", "monument", "mooring", "morsel", "mount",
	"mulberry", "mull", "myth", "name", "nap", "narrows", "niche", "night",
	"norm", "north", "noun", "oat", "offering", "onset", "order", "origin",
	"outlet", "outreach", "pane", "parch", "parsley", "patch", "pattern", "pave",
	"pen", "pickle", "pier", "pipe", "pitch", "pivot", "plow", "pocket",
	"pod", "poise", "pollen", "poppy", "pore", "portal", "powder", "press",
	"prose", "psalm", "quay", "quench", "rack", "raft", "rain", "realm",
	"recess", "record", "relic", "remnant", "renown", "report", "rest", "return",
	"rift", "rim", "rind", "rise", "ritual", "rivulet", "robin", "rook",
	"roost", "ruin", "runnel", "sapling", "scarp", "scent", "scope", "scrub",
	"seam", "shelter", "shoal", "shrine", "sierra", "silhouette", "sinew", "slab",
	"slip", "snail", "song", "source", "sprig", "squad", "squall", "stalk",
	"stir", "stock", "storm", "stove", "stratum", "straw", "stripe", "swirl",
	"tank", "taproot", "tarpon", "terrace", "thatch", "thorn", "tinder", "toll",
	"tome", "topsoil", "trace", "tract", "trench", "trestle", "trunk", "tuber",
	"tundra", "turf", "umber", "union", "upland", "vale", "vane", "vapor",
	"venture", "vestige", "vetch", "village", "violet", "vole", "wake", "ward",
	"warp", "weasel", "wedge", "weir", "wetland", "wick", "wren", "yard",
	"yield", "yolk", "zenith", "album", "alcazar", "algae", "aloft", "ambit",
	"ambush", "ament", "amice", "amir", "ammo", "amulet", "anagram", "ancho",
	"andes", "andron", "anew", "anil", "anon", "anther", "anvil", "aorta",
	"apron", "apt", "arbiter", "arborist", "ardor", "argot", "argyle", "armlet",
	"armory", "arow", "arroba", "artisan", "asana", "ascent", "aster", "astral",
	"attic", "augur", "auric", "aurum", "axon", "babble", "bairn", "ballot",
	"balm", "balsam", "barb", "bard", "basalt", "basket", "baste", "batten",
	"bauble", "beckon", "beggar", "belfry", "beret", "billow", "binnacle", "bison",
	"bivouac", "blade", "blanket", "bleat", "bobbin", "bodkin", "bonnet", "bounty",
	"bramble", "breed", "brew", "briar", "brief", "brooch", "buckle", "burl",
	"butter", "button", "buzzard", "calyx", "camber", "camel", "cameo", "canteen",
	"canvas", "caravel", "carrier", "casket", "catkin", "cattle", "caveat", "cellar",
	"centaur", "chalice", "chamois", "char", "charcoal", "cherub", "chest", "chisel",
	"chrysalis", "cider", "citadel", "clang", "clerk", "cloak", "cobweb", "codex",
	"coffer", "coil", "collar", "condor", "conduit", "confine", "consul", "copse",
	"corbel", "cornice", "cotter", "couplet", "crimson", "cruet", "crux", "cubby",
	"cubit", "culvert", "cushion", "dagga", "daisy", "dancer", "darnel", "decor",
	"deed", "deposit", "depth", "dexter", "dibble", "dirge", "dolmen", "dory",
	"double", "dowel", "dowry", "dragon", "drawl", "dray", "dross", "duvet",
	"dwell", "eaglet", "earwig", "elder", "elytra", "enamel", "ensign", "epoch",
	"escarp", "escrow", "esprit", "essence", "extent", "eyelet", "fallow", "fanfare",
	"fascia", "fathom", "feldspar", "fennel", "ferule", "fief", "figment", "finial",
	"fiord", "firkin", "fistle", "fitment", "flagon", "flax", "fleece", "flicker",
	"flier", "flipper", "floss", "flume", "flurry", "footpath", "foray", "fossil",
	"fresco", "frieze", "frill", "fulcrum", "furlong", "furl", "garb", "garth",
	"gauntlet", "gavel", "gazebo", "geyser", "gibbet", "girdle", "gland", "glint",
	"gloss", "glove", "goblet", "godwit", "gorget", "grebe", "greensward", "grouse",
	"gulch", "hackle", "haft", "hairpin", "halter", "hamper", "hanger", "hasp",
}

// GenerateSlug returns a fresh "<adjective>-<noun>" string. Uses
// crypto/rand for the word indices; panics only if the entropy source
// is broken. The returned slug matches the grammar enforced by Validate.
func GenerateSlug() string {
	a := randIndex(len(slugAdjectives))
	n := randIndex(len(slugNouns))
	return fmt.Sprintf("%s-%s", slugAdjectives[a], slugNouns[n])
}

func randIndex(n int) int {
	if n <= 0 {
		return 0
	}
	var buf [4]byte
	if _, err := rand.Read(buf[:]); err != nil {
		panic(fmt.Sprintf("crypto/rand failure: %v", err))
	}
	return int(binary.BigEndian.Uint32(buf[:])) % n
}
